/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ApiPublicPixCreateRouteImport } from './routes/api/public/pix/create'
import { Route as ApiPublicPixStatusRouteImport } from './routes/api/public/pix/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPixCreateRoute = ApiPublicPixCreateRouteImport.update({
  id: '/api/public/pix/create',
  path: '/api/public/pix/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPixStatusRoute = ApiPublicPixStatusRouteImport.update({
  id: '/api/public/pix/status',
  path: '/api/public/pix/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/api/public/pix/create': typeof ApiPublicPixCreateRoute
  '/api/public/pix/status': typeof ApiPublicPixStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/api/public/pix/create': typeof ApiPublicPixCreateRoute
  '/api/public/pix/status': typeof ApiPublicPixStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/api/public/pix/create': typeof ApiPublicPixCreateRoute
  '/api/public/pix/status': typeof ApiPublicPixStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/checkout' | '/api/public/pix/create' | '/api/public/pix/status'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checkout' | '/api/public/pix/create' | '/api/public/pix/status'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/api/public/pix/create'
    | '/api/public/pix/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  ApiPublicPixCreateRoute: typeof ApiPublicPixCreateRoute
  ApiPublicPixStatusRoute: typeof ApiPublicPixStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pix/create': {
      id: '/api/public/pix/create'
      path: '/api/public/pix/create'
      fullPath: '/api/public/pix/create'
      preLoaderRoute: typeof ApiPublicPixCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pix/status': {
      id: '/api/public/pix/status'
      path: '/api/public/pix/status'
      fullPath: '/api/public/pix/status'
      preLoaderRoute: typeof ApiPublicPixStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  ApiPublicPixCreateRoute: ApiPublicPixCreateRoute,
  ApiPublicPixStatusRoute: ApiPublicPixStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
